[project]
name = "rtsm"
version = "0.1.0"
description = "Ranked Test Suite minimisation"
# license-files = ["LICENSE"]
license = { file = "LICENSE" }
authors = [
    {name = "Théo Matricon", email = "theomatricon@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy>=1.22",
    "scikit-learn>=1.0",
    "colorama>=0.4.4",
    "tqdm>=4.63.0",
]

[project.optional-dependencies]
genetic = ["pygad"]


[project.urls]
Homepage = "https://github.com/Theomat/rtsm"
Repository = "https://github.com/Theomat/rtsm.git"


[tool.setuptools]
packages = ['rtsm']